### ISSUE TITLE
A list of things to consider

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/salti-admin#1]
Comments on index.js refer to line numbers from https://github.com/thaliproject/salti-admin/blob/ebed12403ce7a6ac2d4b40f0e752615ed1ccb030/lib/index.js
- [ ] Please fix the license, the copyright should belong to Microsoft
- [ ] Why isn't mocha listed in devDependencies in config.json?
- [ ] In index.js what is require('debug')? What library is that? There aren't any dependencies listed for production. For someone who installs without the dev dependencies (e.g. a production build) aren't they going to get an error either on the require or on the function call on a null object?
- [ ] Why do you need line 7 in index.js?
- [ ] Also, please don't use exports, instead just use module.exports. It makes our style consistent.
- [ ] In the example you tell people to set the Authorization header as 'CLEAR ' + secret but in the code you added 'CLEAR ' automatically. So wouldn't the authorization header end up as 'CLEAR CLEARasdlf;jaslfkjsa'?
- [ ] In setSecret if a prefix is set then the secret is returned? Shouldn't it be that if the prefix is set then we use the prefix otherwise we use CLEAR? I also would have expected the setSecret function to return the secret (yes, I do see getSecret).
- [ ] In generateSecret I think the normal approach is to use 'cb' (short for callBack) rather than 'next'. I realize this is confusing because Express uses 'next' but that has a very specific and limited semantic, it means continue processing the call or not. But in generateSecret you are just using a generic callback so cb would be more appropriate. Personally I would have just put in a dependency on lie and used a promise. Callbacks are so... naughties.
- [ ] Please run our JSCS annd JShint config files on this code. Line 26 for example wouldn't pass.
- [ ] In line 36 we throw if there are no headers at all. That seems dangerous as it creates a really trivial denial of service attack where if someone can figure out how to send a HTTP request that shows up in express without headers then they can kill our server. Shouldn't we just respond with a 401?
- [ ] Am I halucinating or is index.js essentially static? That is, if two different files in a node.js program both require salti then they will both get the same self object? That seems bad. I would suggest that a more robust solution would be to define salti as a newable object. Then state becomes very clear. In other words module.exports = salti where there is a function salti() {} and methods like setSecret, getSecret, etc. become prototypes on that newable object.
- [ ] The ability to get a secret straight from the app object just feels sorta odd. Almost like a back door. Why not save some testing and just specify that the secret has to be provided in the constructor of the newable object? If a secret isn't provided in the constructor then it should be automatically generated and available as a prototype method getSecret. I would then get rid of setSecret all together. Heck, to save time and simplify testing I'm fine if we don't even allow the secret to be provided in the constructor at all. Instead whenever we run we just generate a secret and it's up to the caller to call getSecret to retrieve it and share it as necessary. This would also let us get rid of lines 51/52 since we would be guaranteed that there is always a secret.
- [ ] Line 54 is dangerous for a couple of different reasons. First off using '!=' for comparison is just dangerous. It allows for some fairly nasty Javascript object casting behavior that could get us in trouble. I warned you this would be the hard part. I would suggest just replacing it with https://www.npmjs.com/package/secure-compare and calling it a day. It also protects against the attack I mentioned where someone tries to guess a password via a timing attack.
- [ ] Could you please set up something like Travis to automatically test the code on each check in and put a badge in GitHub to tell us if tests are passing?
- [ ] In test-basic.js I would expect a test to confirm that the buffer is the right size. You can expose the default buffer size as a property on the static newable object (e.g. admin.defaultSecretSizeInBytes or admin.prototype.defaultSecretSizeInBytes, for no good reason I tend to have a preference for the former over the later). I would also expect a test showing that setSecret works although if you adopt my proposal above you won't need that.
- [ ] In test-adminacl I think a bunch of the descriptions aren't right including, for example, lines 53, 64, 88 and 112.
- [ ] Just for chuckles I would include at least one request with a request body and see that it is both properly accepted and rejected.
- [ ] What is the difference between test-adminacl.js and test-adminacl-p2.js? p2 says something about crypto but I don't see anything about it. Sorry if 'm being slower than usual. Also you set up a get and post endpoint but only test get.

**Comment by cicorias** [comment]
Comments on index.js refer to line numbers from https://github.com/thaliproject/salti-admin/blob/ebed12403ce7a6ac2d4b40f0e752615ed1ccb030/lib/index.js
- [X] Please fix the license, the copyright should belong to Microsoft
- [X] Why isn't mocha listed in devDependencies in config.json?

> Mocha is installed globally `npm install -g mocha` - see [Mocha](http://mochajs.org)
> BUT, i've added it as alocal dev dependancy as that is also what Travis requires. `npm test` in `packages.json` also updated.
- [X] In index.js what is require('debug')? What library is that? There aren't any dependencies listed for production. For someone who installs without the dev dependencies (e.g. a production build) aren't they going to get an error either on the require or on the function call on a null object?

> fixed
> this package is also the standard debug tool used by Express, PouchDB - it's a common debug to console package.
- [X] Why do you need line 7 in index.js?

> this resets exports to module.exports and the package itself. Common pattern in CommonJs modules. 
- [X] Also, please don't use exports, instead just use module.exports. It makes our style consistent.

> updated.
- [X] In the example you tell people to set the Authorization header as 'CLEAR ' + secret but in the code you added 'CLEAR ' automatically. So wouldn't the authorization header end up as 'CLEAR CLEARasdlf;jaslfkjsa'?

> On the "client" side where you setup ajax.agentOptions you need to set the header to `CLEAR foobar`, nothing automatic is there.
> On the server side, the `setSecret` if it isn't passed a 'prefix', it sets it to `CLEAR` - otherwise, it will take a prefix.
- [X] In setSecret if a prefix is set then the secret is returned? Shouldn't it be that if the prefix is set then we use the prefix otherwise we use CLEAR? I also would have expected the setSecret function to return the secret (yes, I do see getSecret).

> nothing is returned by `setSecret` - it sets a property on the object to the secret. If the library is just used as is, there is no real reason to `getSecret` unless setting it in Express `app.set(secret)` or something similar. 
- [X] In generateSecret I think the normal approach is to use 'cb' (short for callBack) rather than 'next'. I realize this is confusing because Express uses 'next' but that has a very specific and limited semantic, it means continue processing the call or not. But in generateSecret you are just using a generic callback so cb would be more appropriate. Personally I would have just put in a dependency on lie and used a promise. Callbacks are so... naughties.

> updated.
- [X] Please run our JSCS annd JShint config files on this code. Line 26 for example wouldn't pass.

>  updated
- [X] In line 36 we throw if there are no headers at all. That seems dangerous as it creates a really trivial denial of service attack where if someone can figure out how to send a HTTP request that shows up in express without headers then they can kill our server. Shouldn't we just respond with a 401?

> The lack of headers really means something is misconfigured as there is always at least 1 - the Methoc (`GET|POST`...).  But, i'll set this not to toss an exception.
- [X] Am I halucinating or is index.js essentially static? That is, if two different files in a node.js program both require salti then they will both get the same self object? That seems bad. I would suggest that a more robust solution would be to define salti as a newable object. Then state becomes very clear. In other words module.exports = salti where there is a function salti() {} and methods like setSecret, getSecret, etc. become prototypes on that newable object.

> No, each `var thing1 = require('lib');` is an object itself, another `var thing2 = require('lib');` is a completly different object and not a shared object / static object.
- [X] The ability to get a secret straight from the app object just feels sorta odd. Almost like a back door. Why not save some testing and just specify that the secret has to be provided in the constructor of the newable object? If a secret isn't provided in the constructor then it should be automatically generated and available as a prototype method getSecret. I would then get rid of setSecret all together. Heck, to save time and simplify testing I'm fine if we don't even allow the secret to be provided in the constructor at all. Instead whenever we run we just generate a secret and it's up to the caller to call getSecret to retrieve it and share it as necessary. This would also let us get rid of lines 51/52 since we would be guaranteed that there is always a secret.

> A secret problaby is something the App determines, not this library. While it offers a `generateSecret` it doesn't need it. The `getSecret` is only needed if there's something that requires an API call -like you mentioned. However, using the library as is with an externally generated secret you would never need to call `getSecret` - just `setSecret` which returns nothing.
> 
> I could certainly add a constructor that would be default take a parameter, but you can also just use a fluent approach `var acl = require('salti-admin').setSecret('mysecret');`
- [X] Line 54 is dangerous for a couple of different reasons. First off using '!=' for comparison is just dangerous. It allows for some fairly nasty Javascript object casting behavior that could get us in trouble. I warned you this would be the hard part. I would suggest just replacing it with https://www.npmjs.com/package/secure-compare and calling it a day. It also protects against the attack I mentioned where someone tries to guess a password via a timing attack.

> updated
- [X] Could you please set up something like Travis to automatically test the code on each check in and put a badge in GitHub to tell us if tests are passing?

> TODO
- [X] In test-basic.js I would expect a test to confirm that the buffer is the right size. You can expose the default buffer size as a property on the static newable object (e.g. admin.defaultSecretSizeInBytes or admin.prototype.defaultSecretSizeInBytes, for no good reason I tend to have a preference for the former over the later). I would also expect a test showing that setSecret works although if you adopt my proposal above you won't need that.

> TODO:
- [X] In test-adminacl I think a bunch of the descriptions aren't right including, for example, lines 53, 64, 88 and 112.

> updated.
- [X] Just for chuckles I would include at least one request with a request body and see that it is both properly accepted and rejected.

> TODO:
- [X] What is the difference between test-adminacl.js and test-adminacl-p2.js? p2 says something about crypto but I don't see anything about it. Sorry if 'm being slower than usual. Also you set up a get and post endpoint but only test get.

> just to keep test.js file sizes smaller - split only to help manage.
